@baseURL=http://localhost:8080/api/v1/community


### CREATE COMMUNITY
POST {{baseURL}}
Content-Type: application/json

{
    "name": "Community 2",
    "descr": "Community 2",
    "companyId":1,
    "logoURL":"http://www.google.com",
    "bannerURL":"http://www.google.com"
}

### EDIT COMMUNITY
PUT {{baseURL}}/1
Content-Type: application/json

{
    "name": "Community 1",
    "descr": "Community 1 updated",
    "companyId":1,
    "logoURL":"http://www.google.com/updated",
    "bannerURL":"http://www.google.com/updated"
}

### GET COMMUNITY BY ID
GET {{baseURL}}/1

### GET COMMUNITY BY COMPANY ID
GET {{baseURL}}/company/1

### DELETE COMMUNITY
DELETE {{baseURL}}/2
