

@baseURL=http://localhost:8080/api/v1/postChannel

#### CREATE POST CHANNEL
POST {{baseURL}}
Content-Type: application/json

{
  "name": "test1",
  "communityId": 1,
    "entryFee":342,
    "logoURL":"2342",
    "isAnnouncement":true
}

### GET POST CHANNEL BY ID
GET {{baseURL}}/1

### GET ALL POSTS IN COMMUNITY
GET {{baseURL}}/community/1

### EDIT POST CHANNEL
POST {{baseURL}}/1
Content-Type: application/json

{
  "name": "test2",
  "communityId": 1,
    "entryFee":3422,
    "logoURL":"logoURL",
    "isAnnouncement":false
}


### DELETE POST CHANNEL
DELETE {{baseURL}}/2